// This enum was generated by Dialoguer
public enum DialoguerDialogues{
	Generic = 0,
	OldSchoolRPG = 1,
	NextGen = 2,
	Test = 3,
	Missingeyes = 4,
	Missingmouth = 5,
	Missingnose = 6,
	Snowmancomplete = 7,
	Intro = 8,
}
